name: InternetNZ IRMA Backend

on:
  push:

jobs:
  deployment:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements.dev.txt
          pip install -r requirements.deploy.txt
      - name: Lint
        run: |
          ./scripts/linter.sh
      - name: Package Audit
        run: |
          ./scripts/package-audit.sh
      - name: Code Security Check
        run: |
          ./scripts/code_security_check.sh
      - name: Deploy demo
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
        run: |
          python -m venv venv
          . ./venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements.deploy.txt
          scripts/zappa-deploy.sh demo ${{ secrets.SINGLE_SOURCE_API_KEY }}
